### ISSUE TITLE
How to assign Coordinates datatype?

### ISSUE THREAD

**Issue by loukitkhemka** [mjaric/google-maps-ng2#1]
How do I assign Datatype for origin and destinations?

**Comment by mjaric** [comment]
Do you refer to directions? If so, it can be any of the types listed for instance [here ](https://github.com/mjaric/google-maps-ng2/blob/8ae4498d4a1f3a75fd6517e2cd96d94cadbfa918/src/directives/google-map-directions.ts#L26-L40)

**Comment by mjaric** [comment]
Btw Coordinates are browser built in type. Check it [here ](https://developer.mozilla.org/en-US/docs/Web/API/Coordinates) and usage [here](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation)
