### ISSUE TITLE
Opaquetoken is deprecated since version 4

### ISSUE THREAD

**Issue by SanderElias** [mjaric/google-maps-ng2#3]
in [this line](https://github.com/mjaric/google-maps-ng2/blob/master/src/loaders/lazy-google-maps-api-loader.ts#L4) of code you are still using OpaqueToken. This is deprecated form 4 on, and removed in 5. Can you update?

**Comment by SanderElias** [comment]
did a [PR](https://github.com/mjaric/google-maps-ng2/pull/4) to fix this.

**Comment by mjaric** [comment]
merged and pushed to npmjs.
Thank you
